Repository jwplayer/ott-web-app, pull requests merged in 2024-06, with the labels that each got.

#541 Fix / waiting for payment PPV/TVOD offers
  packages/common/src/controllers/AccountController.ts
  packages/common/src/controllers/CheckoutController.ts
  packages/common/src/services/integrations/jwp/JWPCheckoutService.ts
  packages/hooks-react/src/useCheckAccess.ts
  packages/ui-react/src/components/WaitingForPayment/WaitingForPayment.tsx
  platforms/web/test-e2e/utils/constants.ts
  yarn.lock
Labels: JWP Audit

#482 Feat / improve generate translations script
  .github/workflows/release-create-release-candidate-branch.yml
  i18next-parser.config.js
  knip.config.ts
  package.json
  platforms/web/i18next-parser.config.js
  platforms/web/package.json
  platforms/web/public/locales/en/common.json
  platforms/web/public/locales/en/country.json
  platforms/web/public/locales/en/us_state.json
  platforms/web/public/locales/en/user.json
  platforms/web/public/locales/es/common.json
  platforms/web/public/locales/es/country.json
  platforms/web/public/locales/es/us_state.json
  platforms/web/public/locales/es/user.json
  platforms/web/src/i18n/resources.ts
  scripts/i18next/generate.js
  yarn.lock
Labels: JWP Audit, Needs discussion

#561 Release Candidate - v6.3.0
  CHANGELOG.md
  package.json
  packages/common/src/constants.ts
  packages/common/src/paths.tsx
  packages/common/src/services/ApiService.ts
  packages/common/src/utils/configSchema.ts
  packages/common/src/utils/liveEvent.ts
  packages/common/src/utils/media.ts
  packages/common/src/utils/urlFormatting.ts
  packages/common/types/config.ts
  packages/common/types/content-list.ts
  packages/common/types/custom-params.ts
  packages/common/types/playlist.ts
  packages/hooks-react/src/usePlaylist.ts
  packages/hooks-react/src/usePlaylists.ts
  packages/hooks-react/src/useSearch.ts
  packages/ui-react/src/components/Shelf/Shelf.tsx
  packages/ui-react/src/containers/Layout/Layout.tsx
  packages/ui-react/src/containers/SidebarContainer/SidebarContainer.tsx
  packages/ui-react/src/pages/ScreenRouting/MediaScreenRouter.tsx
  packages/ui-react/src/pages/ScreenRouting/PlaylistScreenRouter.tsx
  platforms/web/src/containers/AppRoutes/AppRoutes.tsx
  platforms/web/src/screenMapping.ts
Labels: release-candidate
